# Jekyll site config

title: "Chris Chow"
description: >
  The Personal Portfolio Website is a professional platform that showcases 
  the userâ€™s skills, projects, and academic background. It provides employers 
  with an accessible, centralized overview of his/her qualifications using a clean 
  and cost-efficient GitHub Pages framework.
url: "https://chrischow1.github.io"
baseurl: "/PersonalPortfolioWebsite"

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

# Build settings
# Sass disabled (using a static CSS file in assets/css/main.css)

# Navbar links
nav:
  - title: "Home"
    url: "/"
  - title: "SKills"
    url: "/skills/"
  - title: "Projects"
    url: "/projects/"
  - title: "Work Experience"
    url: "/work_experience/"
  - title: "Resume"
    url: "/resume/"

# Profile info
profile:
  name: "Chris Chow"  
  title: "M.S. Electrical Engineering Student"
  affiliation: "California State Polytechnic University, Pomona"
  education: "B.S. Electrical Engineering, California State University, Fullerton"
  primary_email: "chriscc0719@gmail.com"
  work_email: "ch0wcc19@gmail.com"
  school_email: "chrischow1@cpp.edu"
  phone: "+1 (626) 679-7202"
  location: "Hacienda Heights, CA"
  linkedin: "https://www.linkedin.com/in/chris-chow-108b6b224"
  github: "https://github.com/chrischow1"
  headshot: "/assets/img/headshot.svg"

# Footer
footer_note: "Updated February 2026"
